version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      codeql:
        patterns:
          - github/codeql-action/*
      toolkit-workflows:
        patterns:
          - victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml
          - victron-venus/venus-os-ci-toolkit/.github/workflows/auto-merge.yml
